spring:
  data:
    mongodb:
      uri: mongodb+srv://omprasad7875:om78prasad57@cluster0.twnwfni.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /


weather_api_key: ce8a9ac2f84c43198a6a669207691738
