spring.application.name=Journal

spring.data.mongodb.uri=mongodb+srv://omprasad7875:om78prasad57@cluster0.twnwfni.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
#spring.data.mongodb.username=myJournalUser
#spring.data.mongodb.password=myPassword
spring.data.mongodb.auto-index-creation=true

logging.file.name=app.log
#logging.pattern.console=%d{HH:mm:ss} %clr(%-5level) %clr([%class{0}:%line]){cyan} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%class{0}:%line] - %msg%n